baseURL = "https://issunmi.github.io/Changlecommunity/"
languageCode = "zh-cn"
title = "常乐延寿局"
theme = "ananke"

# 默认语言
defaultContentLanguage = "zh"

# 导航菜单
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "服务项目"
    url = "/services/"
    weight = 2
  [[menu.main]]
    name = "关于我们"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "联系我们"
    url = "/contact/"
    weight = 4

# 主题参数（可根据实际修改）
[params]
  description = "*让岁月更长，让安心常在。*"
  author = "常乐延寿局表世界"
  logo = "images/logo.png"          # 将 logo 图片放入 static/images/
  favicon = "images/favicon.png"    # 网站图标
  # 联系方式
  contact_info = "西京市常乐区常乐路88号 | 电话：400-9178-2333 "
  # 底部版权信息
  copyright = "© 2035 常乐延寿局. All rights reserved."

[[params.services]]
  name = "常乐延寿局里世界"
  icon = "images/logo2.png"
  description = "让意识更薄，让恐惧归零。"